### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by josereyesjrz** [oridb/homebrew-myrddin#1]
I’m getting a SHA265 mismatch on the download.
`0cbc0c661d6a1adb4aebcc9119f9b17846d072455be7666abd659e2188ce1e96`
That should be the correct one.

**Comment by oridb** [comment]
I managed to accidentally screw up the tarballs I uploaded for the release. They should be restored, but to avoid any confusion I rolled the 0.1.1 release.

It should be fixed now.
